// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadg9cQHa3ly-Z7OGaTvpfjuKjKi9UlxY',
    appId: '1:1011365801557:web:e87b3497a04d5423d76edc',
    messagingSenderId: '1011365801557',
    projectId: 'plant-disease-app-afb08',
    authDomain: 'plant-disease-app-afb08.firebaseapp.com',
    storageBucket: 'plant-disease-app-afb08.firebasestorage.app',
    measurementId: 'G-BGG61BR2ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEk68CucUqrBooM_v0gLm_AKAYDS43z40',
    appId: '1:1011365801557:android:6b6f13e4d7681574d76edc',
    messagingSenderId: '1011365801557',
    projectId: 'plant-disease-app-afb08',
    storageBucket: 'plant-disease-app-afb08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmqzR8xSGc4lJWDGlLZxWdtcDjHg4fJKc',
    appId: '1:1011365801557:ios:0f2560e1d5dee179d76edc',
    messagingSenderId: '1011365801557',
    projectId: 'plant-disease-app-afb08',
    storageBucket: 'plant-disease-app-afb08.firebasestorage.app',
    iosBundleId: 'com.example.plantDiseaseDetector',
  );
}
